ALTER TABLE tbcliente ADD PRIMARY KEY (CPF);

ALTER TABLE tbcliente ADD COLUMN (DATA_NASCIMENTO DATE);

INSERT INTO tbcliente (CPF, NOME, ENDRECO1, ENDERECO2, BAIRRO, CIDADE,
                        ESTADO, CEP, IDADE, SEXO, LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA, DATA_NASCIMENTO)
VALUES ('45798602595', 'JOÃO DA SILVA JUNIOR', 'RUA PROJETADA 10', '', 'CIC', 'CURITIBA', 'PR', '68890000', 30, 'M',
        10000.00, 2000, 0, '1989-10-05');


SELECT  CPF, NOME FROM tbcliente LIMIT 5;

SELECT CPF AS CPF_CLIENTE, NOME AS NOME_CLIENTE FROM tbcliente;

SELECT * FROM tbcliente WHERE CPF = '1471156710';

SELECT * FROM tbcliente WHERE NOME = 'Fernando Cavalcante';

SELECT * FROM tbcliente WHERE  CIDADE = 'Rio de Janeiro';


SELECT * FROM tbcliente WHERE IDADE < 22;

SELECT * FROM tbcliente WHERE IDADE <> 22;

SELECT * FROM tbcliente WHERE NOME <> 'B';

SELECT * FROM tbcliente WHERE DATA_NASCIMENTO < '1995-01-13';

SELECT * FROM tbcliente WHERE YEAR(DATA_NASCIMENTO) = 2000;

SELECT * FROM tbcliente WHERE MONTH(DATA_NASCIMENTO) = 10;

SELECT * FROM tbcliente WHERE DAY(DATA_NASCIMENTO) = 01;